#cloud-config
output: { all: "| tee -a /tmp/cloud-init-output.log" }

cloud_config_modules:
  - package-update-upgrade-install
  - disk_setup
  - mounts
  - cc_write_files
  - runcmd

write_files:
  - path: /etc/sysconfig/docker-storage-setup
    permissions: 0644
    owner: root
    content: |
        STORAGE_DRIVER=overlay2
        DEVS="/dev/nvme1n1"
        VG=docker-vg
        CONTAINER_ROOT_LV_NAME="dockerlv"
        CONTAINER_ROOT_LV_MOUNT_PATH="/var/lib/docker"
        CONTAINER_ROOT_LV_SIZE=100%FREE
  - path: /tmp/cw-agent-conf.json
    permissions: 0644
    owner: root
    encoding: base64
    content: ${base64encode(cw_agent_conf)}

package_update: true
package_upgrade: true

packages:
  - bash-completion
  - bind-utils
  - bridge-utils
  - git
  - httpd-tools
  - iptables-services
  - kernel
  - kernel-tools
  - kernel-tools-libs
  - kexec-tools
  - libcgroup
  - libselinux-python
  - lvm2
  - net-tools
  - NetworkManager
  - psacct
  - selinux-policy
  - sos
  - wget

fs_setup:
- label: ocp_emptydir
  filesystem: xfs
  device: /dev/nvme2n1
  partition: auto

mounts:
- [ "LABEL=ocp_emptydir", "/var/lib/origin/openshift.local.volumes", xfs, "defaults,gquota" ]

runcmd:
  - yum-config-manager --enable rhui-REGION-rhel-server-extras
  - sed -i 's/SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config
  - rm -f /etc/localtime
  - ln -s /usr/share/zoneinfo/UTC /etc/localtime
  - systemctl restart dbus
  - systemctl daemon-reload
  - systemctl start NetworkManager
  - systemctl enable NetworkManager
  - sed 's/NM_CONTROLLED=no/NM_CONTROLLED=yes/' /etc/sysconfig/network-scripts/ifcfg-eth0 -i
  - systemctl restart NetworkManager
  - systemctl restart network
  - yum install -y docker
  - systemctl enable docker
  - systemctl start --no-block docker
  - echo "UseDNS no" >> /etc/ssh/sshd_config
  - systemctl reload sshd
  - mkdir /etc/aws
  - [ sh, -c, 'echo -e "[Global]\nZone = $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)" > /etc/aws/aws.conf' ]
  - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
  - yum -y --enablerepo=epel install htop
  - yum -y install https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/tmp/cw-agent-conf.json -s
  - echo Defaults:centos \!requiretty >> /etc/sudoers
